version: "3"

services:
  app:
    image: applifting:latest
    volumes:
      - data:/volumes/database
    ports:
      - "8000:80"
  cron:
    image: applifting:latest
    command: ["/launch.sh"]
    volumes:
      - data:/volumes/database

volumes:
  data: